version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      DB_URI: jdbc:mariadb://mariadb:3306/${DB_DATABASE}?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
    command: mvn clean spring-boot:run
    depends_on:
      - mariadb

