
-- Insert product pricing

INSERT INTO `product_price` (`price`, `product_type`) VALUES('52.50', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('29.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('54.67', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('29.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('66.75', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('21.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('49.07', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('21.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('48.70', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('21.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('51.46', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('21.00', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('65.92', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.50', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('47.85', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.50', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('46.00', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.50', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('48.78', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.50', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('69.45', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('12.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('60.87', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('12.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('53.72', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('12.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('53.97', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('12.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('71.49', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.25', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('58.96', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.25', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('54.02', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.25', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('58.22', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.25', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('73.18', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.58', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('59.98', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.58', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('52.50', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.58', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('57.14', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.58', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('74.73', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('60.08', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('54.49', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('57.29', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('13.92', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('71.66', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.26', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('60.82', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.26', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('55.76', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.26', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('58.90', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.26', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('75.06', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.62', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('63.91', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.62', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('67.60', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.62', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('71.66', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.62', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('87.53', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.99', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('72.62', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.99', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('67.01', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.99', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('73.20', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('14.99', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('95.66', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.36', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('77.86', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.36', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('70.78', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.36', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('72.10', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.36', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('92.93', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.75', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('77.58', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.75', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('69.32', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.75', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('76.46', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('15.75', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('98.59', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('16.14', 'LGC');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('85.51', 'ENERGY');
INSERT INTO `product_price` (`price`, `product_type`) VALUES('16.14', 'LGC');

-- Insert load shape premiums

INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.20', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.10', 'MINING');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('1.02', 'INDUSTRIAL');
INSERT INTO `load_shape_premium` (`price`, `customer_type`) VALUES('0.80', 'COMMERCIAL');

-- Insert quarters data

INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2020-7-01 00:00:00', '2020-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2020-10-01 00:00:00', '2020-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2021-1-01 00:00:00', '2021-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2021-4-01 00:00:00', '2021-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2021-7-01 00:00:00', '2021-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2021-10-01 00:00:00', '2021-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2022-1-01 00:00:00', '2022-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2022-4-01 00:00:00', '2022-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2022-7-01 00:00:00', '2022-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2022-10-01 00:00:00', '2022-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2023-1-01 00:00:00', '2023-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2023-4-01 00:00:00', '2023-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2023-7-01 00:00:00', '2023-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2023-10-01 00:00:00', '2023-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2024-1-01 00:00:00', '2024-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2024-4-01 00:00:00', '2024-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2024-7-01 00:00:00', '2024-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2024-10-01 00:00:00', '2024-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2025-1-01 00:00:00', '2025-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2025-4-01 00:00:00', '2025-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2025-7-01 00:00:00', '2025-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2025-10-01 00:00:00', '2025-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2026-1-01 00:00:00', '2026-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2026-4-01 00:00:00', '2026-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2026-7-01 00:00:00', '2026-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2026-10-01 00:00:00', '2026-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2027-1-01 00:00:00', '2027-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2027-4-01 00:00:00', '2027-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2027-7-01 00:00:00', '2027-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2027-10-01 00:00:00', '2027-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2028-1-01 00:00:00', '2028-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2028-4-01 00:00:00', '2028-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2028-7-01 00:00:00', '2028-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2028-10-01 00:00:00', '2028-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2029-1-01 00:00:00', '2029-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2029-4-01 00:00:00', '2029-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2029-7-01 00:00:00', '2029-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2029-10-01 00:00:00', '2029-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2030-1-01 00:00:00', '2030-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2030-4-01 00:00:00', '2030-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2030-7-01 00:00:00', '2030-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2030-10-01 00:00:00', '2030-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2031-1-01 00:00:00', '2031-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2031-4-01 00:00:00', '2031-6-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2031-7-01 00:00:00', '2031-9-30 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2031-10-01 00:00:00', '2031-12-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2032-1-01 00:00:00', '2032-3-31 23:59:59');
INSERT INTO `quarterly_price` (`quarter_start`, `quarter_end`) VALUES('2032-4-01 00:00:00', '2032-6-30 23:59:59');

INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('1', '1');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('1', '2');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('1', '3');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('2', '4');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('2', '5');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('2', '6');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('3', '7');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('3', '8');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('3', '9');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('4', '10');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('4', '11');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('4', '12');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('5', '13');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('5', '14');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('5', '15');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('6', '16');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('6', '17');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('6', '18');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('7', '19');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('7', '20');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('7', '21');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('8', '22');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('8', '23');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('8', '24');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('9', '25');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('9', '26');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('9', '27');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('10', '28');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('10', '29');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('10', '30');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('11', '31');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('11', '32');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('11', '33');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('12', '34');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('12', '35');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('12', '36');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('13', '37');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('13', '38');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('13', '39');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('14', '40');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('14', '41');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('14', '42');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('15', '43');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('15', '44');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('15', '45');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('16', '46');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('16', '47');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('16', '48');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('17', '49');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('17', '50');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('17', '51');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('18', '52');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('18', '53');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('18', '54');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('19', '55');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('19', '56');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('19', '57');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('20', '58');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('20', '59');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('20', '60');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('21', '61');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('21', '62');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('21', '63');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('22', '64');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('22', '65');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('22', '66');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('23', '67');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('23', '68');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('23', '69');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('24', '70');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('24', '71');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('24', '72');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('25', '73');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('25', '74');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('25', '75');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('26', '76');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('26', '77');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('26', '78');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('27', '79');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('27', '80');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('27', '81');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('28', '82');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('28', '83');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('28', '84');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('29', '85');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('29', '86');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('29', '87');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('30', '88');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('30', '89');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('30', '90');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('31', '91');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('31', '92');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('31', '93');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('32', '94');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('32', '95');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('32', '96');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('33', '97');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('33', '98');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('33', '99');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('34', '100');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('34', '101');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('34', '102');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('35', '103');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('35', '104');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('35', '105');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('36', '106');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('36', '107');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('36', '108');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('37', '109');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('37', '110');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('37', '111');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('38', '112');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('38', '113');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('38', '114');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('39', '115');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('39', '116');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('39', '117');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('40', '118');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('40', '119');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('40', '120');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('41', '121');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('41', '122');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('41', '123');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('42', '124');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('42', '125');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('42', '126');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('43', '127');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('43', '128');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('43', '129');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('44', '130');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('44', '131');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('44', '132');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('45', '133');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('45', '134');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('45', '135');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('46', '136');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('46', '137');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('46', '138');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('47', '139');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('47', '140');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('47', '141');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('48', '142');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('48', '143');
INSERT INTO `quarterly_price_load_shape_premiums` (`quarterly_price_id`, `load_shape_premiums_id`) VALUES('48', '144');

INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('1', '1');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('1', '2');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('2', '3');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('2', '4');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('3', '5');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('3', '6');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('4', '7');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('4', '8');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('5', '9');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('5', '10');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('6', '11');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('6', '12');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('7', '13');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('7', '14');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('8', '15');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('8', '16');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('9', '17');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('9', '18');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('10', '19');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('10', '20');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('11', '21');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('11', '22');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('12', '23');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('12', '24');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('13', '25');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('13', '26');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('14', '27');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('14', '28');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('15', '29');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('15', '30');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('16', '31');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('16', '32');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('17', '33');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('17', '34');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('18', '35');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('18', '36');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('19', '37');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('19', '38');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('20', '39');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('20', '40');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('21', '41');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('21', '42');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('22', '43');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('22', '44');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('23', '45');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('23', '46');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('24', '47');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('24', '48');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('25', '49');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('25', '50');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('26', '51');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('26', '52');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('27', '53');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('27', '54');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('28', '55');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('28', '56');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('29', '57');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('29', '58');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('30', '59');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('30', '60');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('31', '61');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('31', '62');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('32', '63');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('32', '64');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('33', '65');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('33', '66');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('34', '67');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('34', '68');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('35', '69');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('35', '70');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('36', '71');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('36', '72');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('37', '73');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('37', '74');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('38', '75');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('38', '76');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('39', '77');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('39', '78');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('40', '79');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('40', '80');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('41', '81');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('41', '82');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('42', '83');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('42', '84');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('43', '85');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('43', '86');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('44', '87');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('44', '88');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('45', '89');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('45', '90');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('46', '91');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('46', '92');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('47', '93');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('47', '94');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('48', '95');
INSERT INTO `quarterly_price_product_prices` (`quarterly_price_id`, `product_prices_id`) VALUES('48', '96');
